@startuml Sequence_GPI

title Processus d'alimentation automatique de la base GPI

autonumber

participant "Poste client" as PC
participant "Contrôleur de domaine" as DC
participant "Script d'ouverture de session" as Script
participant "WinAudit" as WA
collections "Dossier Audits" as Share
participant "Service d'importation" as Import
database "Base de données GPI" as DB

loop À chaque ouverture de session

    PC -> DC : Authentification

    alt Authentification réussie

        DC -> Script : Exécuter le script
        Script -> WA : Lancer l'inventaire

        WA -> PC : Collecter les informations
        WA --> Share : Déposer le fichier TXT

        Import -> Share : Détecter le nouveau fichier
        Share --> Import : Transmettre le fichier

        Import -> DB : Créer ou mettre à jour l'actif

        DB --> Import : Résultat de l'opération

    else Authentification échouée

        DC --> PC : Accès refusé

    end

end

@enduml