@startuml GPI_UseCase

left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome

actor "Utilisateur" as User
actor "Administrateur" as Admin
actor "Visiteur" as Visitor
actor "Contrôleur de domaine" as DC
actor "WinAudit" as WinAudit

User <|-- Admin
User <|-- Visitor

rectangle "Application Web GPI" {

    usecase "S'authentifier" as Login

    package "Gestion du parc informatique" {

        usecase "Gérer les actifs" as ManageAssets
        usecase "Ajouter un actif" as Add
        usecase "Consulter un actif" as View
        usecase "Modifier un actif" as Update
        usecase "Supprimer un actif" as Delete
        usecase "Rechercher un actif" as Search

    }

    package "Cartographie" {

        usecase "Consulter le plan\n du bâtiment" as Map

    }

    package "Maintenance" {

        usecase "Gérer les notifications\n de panne" as Notify

    }

    package "Synchronisation" {

        usecase "Importer automatiquement\n les informations des machines" as Import

        usecase "Mettre à jour\n l'inventaire" as SyncDB

    }

}

User --> Login

Admin --> ManageAssets
Admin --> Notify
Admin --> Import
Admin --> Map

Visitor --> Map

ManageAssets ..> Add : <<include>>
ManageAssets ..> View : <<include>>
ManageAssets ..> Update : <<include>>
ManageAssets ..> Delete : <<include>>
ManageAssets ..> Search : <<include>>

DC --> WinAudit
WinAudit --> Import

Import ..> SyncDB : <<include>>

@enduml