# Generated by Django 6.0.7 on 2026-09-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='fabricant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipement',
            name='modele',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipement',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
