# Generated by Django 6.0.7 on 2026-09-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_equipement_fabricant_equipement_modele_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='actif',
        ),
        migrations.AddField(
            model_name='equipement',
            name='etat',
            field=models.CharField(choices=[('EN_SERVICE', 'En service'), ('EN_PANNE', 'En panne'), ('EN_MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='EN_SERVICE', max_length=20),
        ),
        migrations.AddField(
            model_name='equipement',
            name='situation',
            field=models.CharField(choices=[('AFFECTE', 'Affecte'), ('EN_STOCK', 'Stock')], default='AFFECTE', max_length=20),
        ),
    ]
