# Generated by Django 6.0.7 on 2026-09-17 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_remove_equipement_actif_equipement_etat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu'), ('ANNULE', 'Annulé')], default='OUVERT', max_length=20)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('commentaire_resolution', models.TextField(blank=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_panne', to='inventaire.equipement')),
            ],
        ),
    ]
