# Generated by Django 6.0.7 on 2026-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_ticketpanne'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='condition_stock',
            field=models.CharField(blank=True, choices=[('NEUF', 'Neuf'), ('OCCASION', 'Occasion'), ('RECONDITIONNE', 'Reconditionne')], max_length=20, null=True),
        ),
    ]
