# Generated by Django 6.0.7 on 2026-09-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0005_equipement_condition_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpanne',
            name='priorite',
            field=models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='NORMALE', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketpanne',
            name='titre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ticketpanne',
            name='type',
            field=models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('RECLAMATION', 'Réclamation')], default='MAINTENANCE', max_length=20),
        ),
    ]
