# Generated by Django 6.0.7 on 2026-10-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0008_positionner_equipements_affectes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='etage',
            unique_together={('batiment', 'nom'), ('batiment', 'numero')},
        ),
    ]
