# Generated by Django 6.0.7 on 2026-09-07 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_connexionaudit'),
        ('inventaire', '0002_equipement_fabricant_equipement_modele_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapportaudit',
            name='date_importation',
        ),
        migrations.RemoveField(
            model_name='rapportaudit',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='rapportaudit',
            name='nom_fichier',
        ),
        migrations.RemoveField(
            model_name='rapportaudit',
            name='traite',
        ),
        migrations.AddField(
            model_name='rapportaudit',
            name='bios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rapportaudit',
            name='date_audit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapportaudit',
            name='donnees_brutes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rapportaudit',
            name='equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_audit', to='inventaire.equipement'),
        ),
        migrations.AddField(
            model_name='rapportaudit',
            name='memoire',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rapportaudit',
            name='processeur',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rapportaudit',
            name='stockage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rapportaudit',
            name='system_exploitation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
